[package]
name = "ophidiedev/replica"
description = "Roblox server to client state replication solution which lets the developer subscribe certain players to certain states. Originally made by loleris. NOT COMPATIBLE WITH OTHER VERSIONS OF REPLICA"
license = "Apache-2.0"
authors = ["loleris","ophidie"]
version = "0.2.0"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]
